[Details]
  Icon = "data/assets/fyne.png"
  Name = "Money Manager Ex"
  ID = "ru.dubrovskih.mmex"
  Version = "0.0.1"
  Build = 1

[Source]
  Repo = "https://github.com/jaennil/sego"
  Dir = "."

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"

[LinuxAndBSD]
  GenericName = "Money Manager Ex"
  Categories = ["Development"]
  Comment = "Money manager ex description"
  Keywords = ["money", "manager"]
